version: "2.1"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/anuncios
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=anuncios
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 30s
      retries: 10

  